run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - misspell
    - unconvert
    - whitespace

linters-settings:
  govet:
    enable-all: false
  misspell:
    locale: US

issues:
  exclude-dirs:
    - bin
    - dist
    - new-api-me
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
