blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Levi9111/create-express-modular-go/discussions
    about: Ask questions, share ideas, and connect with other users.
  - name: 📦 Original npm Package
    url: https://www.npmjs.com/package/create-express-modular
    about: Check the Node.js implementation on npm.
