package generator

import (
	"fmt"
	"path/filepath"
)

func scaffoldDocs(opts ProjectOptions) error {
	root := opts.ProjectPath

	readme := fmt.Sprintf(`# %s

Modular, domain-driven Express + TypeScript backend.

> Scaffolded with [create-express-modular](https://create-express-modular.lovable.app/) (cem)

---

## Stack
- **Runtime**: Node.js + Express
- **Language**: TypeScript
- **Database**: %s
- **Validation**: %s
- **Authentication**: %t
- **Docker**: %t
- **Swagger Docs**: %t

---

## Getting Started

### 1. Install dependencies
`+"```bash"+`
npm install
`+"```"+`

### 2. Configure environment
Check `+"`.env`"+` and adjust database credentials as necessary.

### 3. Start development server
`+"```bash"+`
npm run dev
`+"```"+`

Server runs at `+"http://localhost:5000"+`.
API documentation is available at `+"http://localhost:5000/docs"+`.

---

## Available Commands
- `+"`npm run dev`"+` — Start development server with hot reload
- `+"`npm run build`"+` — Compile TypeScript to dist/
- `+"`npm run start`"+` — Start production server
- `+"`npm run check`"+` — Run type-check, lint, and format checks

---

Built with [create-express-modular](https://create-express-modular.lovable.app/).
`, opts.ProjectName, opts.DB, opts.Validator, opts.UseAuth, opts.UseDocker, opts.UseSwagger)

	agentsMd := fmt.Sprintf(`# AGENTS.md — Context for AI Coding Assistants

This project is a modular, domain-driven Express + TypeScript application generated by Create Express Modular.

## Core Rules & Architecture
1. **Domain-Driven Modular Design**:
   - Every feature lives in its own folder under `+"`src/app/modules/<FeatureName>/`"+`
   - Files follow the naming convention:
     - `+"`<feature>.controller.ts`"+` — HTTP request/response handler using catchAsync and sendResponse.
     - `+"`<feature>.service.ts`"+` — Pure business logic and database access.
     - `+"`<feature>.route.ts`"+` — Express Router definitions.
     - `+"`<feature>.interface.ts`"+` — TypeScript interfaces and types.
     - `+"`<feature>.validation.ts`"+` — %s schema validation.
2. **Database**: %s
3. **Validator**: %s
4. **Unified Error Handling**:
   - Always throw `+"`AppError`"+` from `+"`src/app/errors/AppError`"+`
   - All errors are caught by `+"`globalErrorHandler`"+` middleware.
5. **Route Registration**:
   - All feature routes are registered in `+"`src/app/routes/index.ts`"+`
`, opts.Validator, opts.DB, opts.Validator)

	claudeMd := fmt.Sprintf(`# CLAUDE.md — Assistant Guide for %s

## Project Information
- **Project**: %s
- **Database**: %s
- **Validator**: %s
- **Package Manager**: %s

## Development Commands
- `+"`npm run dev`"+`: Start development server
- `+"`npm run build`"+`: Build TypeScript
- `+"`npm run check`"+`: Typecheck and linting
`, opts.ProjectName, opts.ProjectName, opts.DB, opts.Validator, opts.PM)

	if err := writeFile(filepath.Join(root, "README.md"), readme); err != nil {
		return err
	}
	if err := writeFile(filepath.Join(root, "AGENTS.md"), agentsMd); err != nil {
		return err
	}
	return writeFile(filepath.Join(root, "CLAUDE.md"), claudeMd)
}
